/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopRouteImport } from './routes/top'
import { Route as ApiPhotosRouteImport } from './routes/api.photos'
import { Route as PhotosIdRouteImport } from './routes/photos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosRoute = ApiPhotosRouteImport.update({
  id: '/api/photos',
  path: '/api/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIdRoute = PhotosIdRouteImport.update({
  id: '/photos/$id',
  path: '/photos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/top': typeof TopRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos/$id': typeof PhotosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/top': typeof TopRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos/$id': typeof PhotosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/top': typeof TopRoute
  '/api/photos': typeof ApiPhotosRoute
  '/photos/$id': typeof PhotosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/top' | '/api/photos' | '/photos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/top' | '/api/photos' | '/photos/$id'
  id: '__root__' | '/' | '/top' | '/api/photos' | '/photos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopRoute: typeof TopRoute
  ApiPhotosRoute: typeof ApiPhotosRoute
  PhotosIdRoute: typeof PhotosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos': {
      id: '/api/photos'
      path: '/api/photos'
      fullPath: '/api/photos'
      preLoaderRoute: typeof ApiPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$id': {
      id: '/photos/$id'
      path: '/photos/$id'
      fullPath: '/photos/$id'
      preLoaderRoute: typeof PhotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopRoute: TopRoute,
  ApiPhotosRoute: ApiPhotosRoute,
  PhotosIdRoute: PhotosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
